# config for experiments

[ca-HepPh]
kvals = [1, 3, 5, 10, 20, 50] 
muvals = [1e-5, 2e-5, 5e-5, 1e-4, 25e-5, 5e-4,
          1e-3, 2e-3, 5e-3, 1e-2, 25e-3, 5e-2,
          0.1, 0.2, 0.3, 0.4]


[ca-AstroPh]
kvals = [1, 3, 5, 10, 20, 50] 
muvals = [1e-5, 2e-5, 5e-5, 1e-4, 25e-5, 5e-4,
          1e-3, 2e-3, 5e-3, 1e-2, 25e-3, 5e-2,
          0.1, 0.2, 0.3, 0.4]


[deezer]
kvals = [1, 3, 5, 10, 20, 50] 
muvals = [1e-5, 2e-5, 5e-5, 1e-4, 25e-5, 5e-4,
          1e-3, 2e-3, 5e-3, 1e-2, 25e-3, 5e-2,
          0.1, 0.2, 0.3, 0.4]


[facebook]
kvals = [1, 3, 5, 10, 20, 50] 
muvals = [5e-6, 
          1e-5, 2e-5, 5e-5, 1e-4, 25e-5, 5e-4,
          1e-3, 2e-3, 5e-3, 1e-2, 25e-3, 5e-2,
          0.1, 0.2, 0.3, 0.4]


[email-Enron]
kvals = [1, 3, 5, 10] 
muvals = [5e-6, 
          1e-5, 2e-5, 5e-5, 1e-4, 25e-5, 5e-4,
          1e-3, 2e-3, 5e-3, 1e-2, 25e-3, 5e-2,
          0.1, 0.2, 0.3, 0.4]


[dblp]
kvals = [1, 3, 5, 10] 
muvals = [1e-6, 2e-6, 5e-6, 1e-5, 25e-6, 5e-5,
          1e-4, 2e-4, 5e-4, 1e-3, 25e-4, 5e-3,
          0.01, 0.02, 0.05, 0.1, 0.2, 0.3, 0.4]